### ISSUE TITLE
Calling find_package catkin twice drops previous components

### ISSUE THREAD

**Issue by AlexReimann** [pyros-dev/ros1_template#12]
From [here](https://github.com/pyros-dev/ros1_template/blob/c14d62fd89104814384f50a28b6db9ff3f3f1821/ros1_pytemplate/CMakeLists.txt#L12):

```
find_package(catkin REQUIRED
            COMPONENTS
            roslint
)

if (CATKIN_ENABLE_TESTING)
  find_package(catkin REQUIRED
            COMPONENTS
             rostest
  )
endif()
```

This will drop the roslint include, which might be the reason for issue #11 

I copy & pasted that and took me like an hour to figure out why suddenly my package can't find the other package .. ;_;

**Comment by AlexReimann** [comment]
Checked it and yes it drops the previous variables in ``catkin_LIBRARIES``, ``catkin_INCLUDE_DIRS``, ``catkin_LIBRARY_DIRS``, ``catkin_EXPORTED_TARGETS`` when running ``find_package(catkin)``.

The reason in the code is that if ``_CATKIN_FIND_`` is zero. It gets incremented and decremented during the script and ends up being zero again.

I guess that's actually a feature.

**Comment by AlexReimann** [comment]
So should use the ``find_package(catkin)`` only once and for everything else just ``find_package`` I guess..?

**Comment by asmodehn** [comment]
I would think that if it s the CMake's find_package that does this it s
likely a feature... if it s the Catkin's catkinConfig that does this is
likely a bug ( and we should compare that with another existing package
with components like Qt... I might try that next week...)

**Comment by AlexReimann** [comment]
Is in catkinConfig:

[L45](https://github.com/ros/catkin/blob/b05cd262f4aa992856d4470cfc2b1f5e52fabefc/cmake/catkinConfig.cmake.in#L45):
```
if(NOT _CATKIN_FIND_ OR _CATKIN_FIND_ EQUAL 0)
  set(_CATKIN_FIND_ 0)
  if(catkin_FIND_COMPONENTS)
    set(catkin_INCLUDE_DIRS "")
    set(catkin_LIBRARIES "")
    set(catkin_LIBRARY_DIRS "")
    set(catkin_EXPORTED_TARGETS "")
  endif()
endif()

# increment recursion counter
math(EXPR _CATKIN_FIND_ "${_CATKIN_FIND_} + 1")
```

[L121](https://github.com/ros/catkin/blob/b05cd262f4aa992856d4470cfc2b1f5e52fabefc/cmake/catkinConfig.cmake.in#L121):
```
math(EXPR _CATKIN_FIND_ "${_CATKIN_FIND_} - 1")

if(_CATKIN_FIND_ EQUAL 0)
  # store found components (from the fist level only) for validation in catkin_package() that they are build dependencies
  list(APPEND catkin_ALL_FOUND_COMPONENTS ${catkin_FIND_COMPONENTS})
endif()
```

**Comment by asmodehn** [comment]
I registered the issue on catkin repo. https://github.com/ros/catkin/issues/886

I also think we should not use the `find_package(catkin COMPONENTS pkg)`, since there seems to be [no actual need for it](http://wiki.ros.org/catkin/CMakeLists.txt#Why_Are_Catkin_Packages_Specified_as_Components.3F). Proper cmake should be preferred : `find_package(pkg)`.

**Comment by asmodehn** [comment]
Closing since it has been addressed, and we wont wait for the fix.
