### ISSUE TITLE
gitpitch slideshow link broken

### ISSUE THREAD

**Issue by naveedhd** [pyros-dev/ros1_template#24]
gitpitch says:

```
PITCHME.md 404

No GitPitch found for this branch on GitHub.
```

for the link: [https://gitpitch.com/pyros-dev/ros1_template/class?grs=github](https://gitpitch.com/pyros-dev/ros1_template/class?grs=github) in the main page.

**Comment by asmodehn** [comment]
Fixed, Thanks !
