### ISSUE TITLE
346346

### ISSUE THREAD

**Issue by AlexReimann** [pyros-dev/ros1_template#3]
https://github.com/pyros-dev/ros1_template/blob/master/nodes/follower_node.py#L46

**Comment by asmodehn** [comment]
Actually this is a good point : what happens to the return data of a subscriber callback ?

**Comment by AlexReimann** [comment]
Unused?

**Comment by asmodehn** [comment]
No idea, and the wiki section doesnt even specify it : http://wiki.ros.org/roscpp/Overview/Publishers%20and%20Subscribers The Callback signature only talks about function input parameters, nothing about output...

**Comment by asmodehn** [comment]
On python `return` is used by the service to send the response.
But subscriber seems to not do anything with it : http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber(python)#rospy_tutorials.2BAC8-Tutorials.2BAC8-WritingPublisherSubscriber.The_Code-1

putting a comment there instead.
