### ISSUE TITLE
separate msgs package

### ISSUE THREAD

**Issue by asmodehn** [pyros-dev/ros1_template#6]
I have been wondering for a while about separating msgs package...

- what are the actual reasons for people doing it ? scientific ("this workflow is actually broken") or social ("I get a better feeling doing it this way")
- catkin supports having message and code in the same package, even though it s a bit broken (especially in python). How is it in C++ ?
- having two package force people to manage package versions tightly between both, which disorganized teams working with too much code have trouble doing...

@AlexReimann So do we want to do it or not here ?

**Comment by AlexReimann** [comment]
From [here](http://answers.ros.org/question/11835/when-should-i-split-my-code-into-multiple-packages-and-whats-a-good-way-to-split-it/):

> Consider combining message definitions in one or more separate packages. That usually simplifies the dependencies among packages, with nodes depending on the messages, and not so much on each other.

From [here](https://github.com/ethz-asl/ros_best_practices/wiki):

> Create separate packages that contain only messages, services and actions (separation of interface and implementation). 

Basically msgs will be probably uses by multiple packages (at least sender and receiver). To keep the overhead of the dependency low and avoid dependency loops, a separate package is better?

C++ also supports having it in the same package.

**Comment by asmodehn** [comment]
Alright lets always separate message package then.
